env_params:
  n_player: 2
  env_name: "gym CartPole-v1"
  reward: 
  num_envs: 2
  is_obs_continuous: false
  is_act_continuous: false
  obs_type: 
    - "dict"
    - "dict"
  max_step: 3000
  agent_nums: 
    - 1
    - 0
  act_box: 
    discrete_n: 2
policy_params:
  lr: 0.0005
  train_iters: 10
  clip_ratio: 0.3
  target_kl: 0.01
  ent_coef: 0.00
  kl_coef: 0.2
  v_coef: 1.0
  clip_grads: 0.64


  pool_size: 
  mlp_filters: 
    - 100
    - 50
  activation: tanh
  output_activation: 
  kernel_initializer: 
  input_shape: [4]
  act_size: 2

train_params:
  trainer: "Proximal Policy Optimization"
  nn_architecure: "mlp_simple_actor_critic"

  epochs: 50
  steps_per_epoch: 512
  num_mini_batches: 4
  gamma: 0.99
  lam: 1.0
  save_freq: 200

  restore_path: