env_params:
  env_name: "gym CartPole-v1"
  num_envs: 10

policy_params:
  lr: 0.0005
  train_iters: 10
  clip_param: 0.3
  target_kl: 0.01
  ent_coef: 0.00
  kl_coef: 0.2
  vf_loss_coef: 1.0
  clip_grads: 0.64

  nn_architecure: "mlp_simple_actor_critic"
  pool_size: 
  mlp_filters: 
    - 100
    - 50
  activation: relu
  output_activation: 
  kernel_initializer: 
  input_shape: [4]
  act_size: 2

train_params:
  trainer: "Proximal Policy Optimization"


  epochs: 100
  steps_per_epoch: 512
  num_mini_batches: 4
  gamma: 0.99
  lam: 1.0
  save_freq: 200

  restore_path: